name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODBlYTE5NDItZjI3YS00NjQ2LWIxMWUtZDNkMTQyZGMzMDRkIiwidGVuYW50X2lkIjoiZDFkYTk5ZTIxMTZhZjA2OTAwNzQwY2FkNzFhMmU2YTg2ZmE4N2U5NmQ2NjJmYzQ5N2Y5NzZiNTY2NjZkYjcwMSIsImludGVybmFsX3NlY3JldCI6ImJkMWFkOWQ3LWFjZDYtNGM3Zi1iODdjLTIyMDNjOGNlZWYzNyJ9.O3jKa5riYARJ4V99i49Btxn6bMlo04IRGbFhQPdce1k"
JWT_SECRET="Sabdar"